languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "RKey Tech"
 logo = "img/rkeytech.png"
 description = "RKey Tech Home"
 #copyright = "Copy, _right?_ :thinking_face:"

dateFormat = "2 January 2006"

[author]
   name = "Robyn Key"
   image = "img/robyn.jpg"
   headline = "I'm only human; NOT!"
   bio = "Robyn; Has been working in IT since 1998, cutting their teeth on AIX, Solaris, DEC, HP-UX, AS400, FreeBSD, OpenBSD, BSD, Linux of all distros, working as Systems Admin, Network Engineer, Recovery Specialist, and Data Center Manager and would love to get back into the industry again."
   links = [
     { email = "mailto:rkey@rkey.tech" },
     { personal_site = "https://blog.rkey.tech/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { blogger = "https://username.blogspot.com/" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
     { facebook = "https://facebook.com/robwkeytech" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
     { github = "https://github.com/Opekktar" },
     { gitlab = "https://gitlab.com/Opekktar" },
  #   { google = "https://www.google.com/" },
     { instagram = "https://instagram.com/robwkeytech" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/opekktar" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/opekktar" },
  #   { telegram = "https://t.me/opekktar" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://opekktar.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
     { twitter = "https://twitter.com/rkey_tech" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
   ]
